-- =============================================================================
-- OLTP SCHEMA DATA — Belgian Sanitary & Building Materials Distributor
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. MASTER TABLES
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS silver.locations (
    location_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_code         varchar(10)  NOT NULL UNIQUE,
    location_name         varchar(100) NOT NULL,
    location_type         varchar(20)  NOT NULL CHECK (location_type IN ('sanicenter','regional_warehouse')),
    address               varchar(200),
    city                  varchar(100),
    postal_code           varchar(10),
    region                varchar(50),
    storage_capacity_m3   numeric(10,2),
    is_active             boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS silver.suppliers (
    supplier_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code        varchar(10)  NOT NULL UNIQUE,
    supplier_name        varchar(100) NOT NULL,
    contact_name         varchar(100),
    email                varchar(150),
    country              varchar(50),
    avg_lead_time_days   numeric(5,1),
    reliability_score    numeric(3,2) CHECK (reliability_score BETWEEN 0 AND 1),
    is_active            boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS silver.products (
    product_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku               varchar(20)  NOT NULL UNIQUE,
    product_name      varchar(150) NOT NULL,
    category          varchar(50),
    subcategory       varchar(50),
    brand             varchar(50),
    unit_of_measure   varchar(20),
    unit_weight_kg    numeric(8,3),
    unit_price_eur    numeric(10,2),
    lead_time_days    integer,
    min_order_qty     numeric(8,2),
    is_active         boolean NOT NULL DEFAULT TRUE,
    created_at        timestamp NOT NULL DEFAULT now(),
    updated_at        timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS silver.customers (
    customer_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code     varchar(10)  NOT NULL UNIQUE,
    customer_name     varchar(150) NOT NULL,
    customer_type     varchar(30) CHECK (customer_type IN ('plumber','contractor','architect','retailer','individual')),
    address           varchar(200),
    city              varchar(100),
    postal_code       varchar(10),
    region            varchar(50),
    is_professional   boolean NOT NULL DEFAULT TRUE,
    is_active         boolean NOT NULL DEFAULT TRUE
);

-- -----------------------------------------------------------------------------
-- 2. DEPENDENT TABLES
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS silver.product_suppliers (
    id                       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id               integer NOT NULL REFERENCES silver.products(product_id),
    supplier_id              integer NOT NULL REFERENCES silver.suppliers(supplier_id),
    supplier_unit_cost_eur   numeric(10,2),
    supplier_lead_time_days  integer,
    is_preferred             boolean NOT NULL DEFAULT FALSE,
    UNIQUE (product_id, supplier_id)
);

CREATE TABLE IF NOT EXISTS silver.inventory (
    inventory_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id        integer NOT NULL REFERENCES silver.products(product_id),
    location_id       integer NOT NULL REFERENCES silver.locations(location_id),
    qty_on_hand       numeric(10,2) NOT NULL DEFAULT 0,
    qty_reserved      numeric(10,2) NOT NULL DEFAULT 0,
    min_stock_level   numeric(10,2) NOT NULL DEFAULT 0,
    reorder_point     numeric(10,2) NOT NULL DEFAULT 0,
    max_stock_level   numeric(10,2) NOT NULL DEFAULT 0,
    last_updated      timestamp NOT NULL DEFAULT now(),
    UNIQUE (product_id, location_id)
);

CREATE TABLE IF NOT EXISTS silver.sales_orders (
    order_id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id        integer NOT NULL REFERENCES silver.customers(customer_id),
    location_id        integer NOT NULL REFERENCES silver.locations(location_id),
    order_ts           timestamp NOT NULL,
    status             varchar(20) CHECK (status IN ('pending','fulfilled','partial','cancelled')),
    source             varchar(20) CHECK (source IN ('counter','phone','online','erp_import')),
    total_amount_eur   numeric(12,2)
);

CREATE TABLE IF NOT EXISTS silver.sales_order_lines (
    line_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id           integer NOT NULL REFERENCES silver.sales_orders(order_id),
    product_id         integer NOT NULL REFERENCES silver.products(product_id),
    qty_ordered        numeric(10,2),
    qty_fulfilled      numeric(10,2),
    unit_price_eur     numeric(10,2),
    line_total_eur     numeric(12,2)
);

CREATE TABLE IF NOT EXISTS silver.purchase_orders (
    po_id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id         integer NOT NULL REFERENCES silver.suppliers(supplier_id),
    location_id         integer NOT NULL REFERENCES silver.locations(location_id),
    created_at          timestamp NOT NULL,
    expected_delivery   date,
    actual_delivery     date,
    status              varchar(20) CHECK (status IN ('draft','sent','confirmed','received','partial','cancelled')),
    total_cost_eur      numeric(12,2)
);

CREATE TABLE IF NOT EXISTS silver.purchase_order_lines (
    line_id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id               integer NOT NULL REFERENCES silver.purchase_orders(po_id),
    product_id          integer NOT NULL REFERENCES silver.products(product_id),
    qty_ordered         numeric(10,2),
    qty_received        numeric(10,2),
    unit_cost_eur       numeric(10,2),
    line_total_eur      numeric(12,2)
);

CREATE TABLE IF NOT EXISTS silver.inventory_movements (
    movement_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          integer NOT NULL REFERENCES silver.products(product_id),
    location_id         integer NOT NULL REFERENCES silver.locations(location_id),
    movement_type       varchar(20) CHECK (movement_type IN ('sale','po_receipt','adjustment','transfer','initial_stock')),
    qty_delta           numeric(10,2) NOT NULL,
    ref_order_id        integer,
    ref_order_type      varchar(20),
    movement_ts         timestamp NOT NULL,
    notes               text
);
